server:
  port: 8080

spring:
  application:
    name: pv-case-review-backend
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

app:
  bootstrap:
    case-data-path: classpath:data/case_v1.json
